### ISSUE TITLE
prompt address: only derive PK once

### ISSUE THREAD

**Issue by emturner** [trilitech/ledger-app-tezos-wallet#108]
# Goal
When handling `INS_PROMPT_PUBLIC_KEY`, we should only derive the public key once.

# Context

              One thing spotted: we derive pk twice in the prompt flow!

_Originally posted by @emturner in https://github.com/trilitech/ledger-app-tezos-wallet/issues/106#issuecomment-1789387894_

**Comment by ajinkyaraj-23** [comment]
PK is derived twice in promt flow because
1. To show on the device screen the derivation of the PK, we need to derive pk and then create hash. The pk is stored in local variable and the hash is passed along as variable to be displayed on the screen. After which both the hash and pk are not present in memory. 
2. After receiving Accept, the pk is derived again and sent to I/O.

Effectively the solution is to store the PK in global memory when we derive it for the first time. Then if we get Accept we send the pk in global memory via I/O after which we clear the pk in global memory for security purposes. Similarly if the user presses reject, we immediately clear the pk in global memory. 
Does that sound proper approach. Can we reuse some global memory buffer for this?
